level = "category"
id = "02"
beg = 4
count = 5
canon = "ot"

[image]
filename = "00-01c.png"

[[stories]]
id = "04"
image = "obs-en-04-01.jpg"

[[stories]]
id = "05"
image = "obs-en-05-01.jpg"

[[stories]]
id = "06"
image = "obs-en-06-01.jpg"

[[stories]]
id = "07"
image = "obs-en-07-01.jpg"

[[stories]]
id = "08"
image = "obs-en-08-01.jpg"
