level = "category"
id = "03"
beg = 9
count = 6
canon = "ot"

[image]
filename = "00-02d.png"

[[stories]]
id = "09"
image = "obs-en-09-01.jpg"

[[stories]]
id = "10"
image = "obs-en-10-01.jpg"

[[stories]]
id = "11"
image = "obs-en-11-01.jpg"

[[stories]]
id = "12"
image = "obs-en-12-01.jpg"

[[stories]]
id = "13"
image = "obs-en-13-01.jpg"

[[stories]]
id = "14"
image = "obs-en-14-01.jpg"
